server:
  port: 8090
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  #datasource:
  #  url: jdbc:postgresql://localhost:5432/testdb
  #  username: testuser
  #  password: testuser

